spring:
  application:
    name: xmopay-funds
server:
  port: 9091

funds:
  execute:
    enable: true
    stop: false
    messageType: 0
    transferToHost:
logs:
  level: info
  path: ./logs

datasource:
  #是否启用数据库模式
  enable: true
  # 使用druid数据源
  driver-class-name: com.mysql.cj.jdbc.Driver
  type: com.alibaba.druid.pool.DruidDataSource
  url: jdbc:mysql://paycloud.mysql.rds.aliyuncs.com:3308/xmopayv20?autoReconnect=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
  username: xmopay
  password: qj3U8wd3cJ6TDDbOXQxLbIQon7Wy0MQ1SSWCBBI0TXScC1bwT/eWysbh4fZhmlAk8WRBZ9jXTZKVdR70O+oniA==
  # 下面为连接池的补充设置，应用到上面所有数据源中
  # 初始化大小，最小，最大
  initialSize: 1
  minIdle: 3
  maxActive: 20
  # 配置获取连接等待超时的时间
  maxWait: 60000
  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
  timeBetweenEvictionRunsMillis: 60000
  # 配置一个连接在池中最小生存的时间，单位是毫秒
  minEvictableIdleTimeMillis: 30000
  validationQuery: select 'x'
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  # 打开PSCache，并且指定每个连接上PSCache的大小
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20
  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
  filters: config,stat,wall,slf4j
  #打开慢SQL记录
  logSlowSql: true
  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALihc+CoZDAzfMH/IaZ6GCN74Lproainl8ZGeZyAW6Q+Phpr9fuIJaYcdAe1abIu1zF5RNxePcbXzbk2xSf0OeUCAwEAAQ==
  # 合并多个DruidDataSource的监控数据
  #useGlobalDataSourceStat: true

message:
  topics:
    TOPIC_TRADE_PAY_WAIT_SETTLE: tradeRechargeServiceImpl
    TOPIC_TRADE_PAY_REFUND: tradeRefundServiceImpl
